### ISSUE TITLE
Git Clone Fails to Merge

### ISSUE THREAD

**Issue by rolyatwilson** [bitrise-io/steps-git-clone#72]
I'm seeing multiple errors in the Git Clone step.
```
git "init"
Initialized empty Git repository in /bitrise/src/.git/
git "remote" "add" "origin" "git@github.com:<my_repo>.git"
git "fetch" "--depth=1"
git "fetch" "origin" "pull/<my_pr>/head:pull/<my_pr>"
From github.com:<my_repo>
 * [new ref]         refs/pull/<my_pr>/head -> pull/<my_pr>
git "checkout" "master"
Branch master set up to track remote branch master from origin.
Already on 'master'
git "merge" "origin/master"
Already up-to-date.
git "merge" "pull/<my_pr>"
CONFLICT (add/add): Merge conflict in ...
Merge failed, error: exit status 1
Unshallow...
git "fetch" "--unshallow"
git "merge" "pull/<my_pr>"
error: merge is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
ERROR: auto merge, error: merge "pull/<my_pr>": exit status 128
```
I'm currently using build step version 4.0.6 and 4.0.7

**Comment by rolyatwilson** [comment]
My PRs are working with version 4.0.5.

**Comment by bootstraponline** [comment]
I'd like more information about the testing process for the `steps-git-clone` code. This isn't the first time all our builds have broken.

**Comment by viktorbenei** [comment]
Thanks for reporting @rolyatwilson ! It seems the issue is related to the `depth` parameter in your case set to `1`. For some reason `unshallow` doesn't seem to work and without that the PR branch can't be merged.

We'll try to fix this ASAP, in the meantime either use 4.0.5 or remove the `depth` param.

**Comment by viktorbenei** [comment]
@bootstraponline the tests are in the repo, in `bitrise.yml` - this one was added here https://github.com/bitrise-io/steps-git-clone/pull/71/files but it seems we forgot to test something.. will fix the tests too

**Comment by viktorbenei** [comment]
@rolyatwilson do you have the **Manual merge** option set to **no**? This shouldn't happen with the default (**yes**) value https://github.com/bitrise-io/steps-git-clone/blob/master/step.yml#L119

**Comment by bootstraponline** [comment]
yeah we do, we're deleting that also.

**Comment by kdobmayer** [comment]
Hi @rolyatwilson ,

Thanks for reporting! We released a new version ([4.0.8](https://github.com/bitrise-io/steps-git-clone/releases/tag/4.0.8)) with the bugfix.

**Comment by raquezha** [comment]
I still experience this issue. any update?

https://discuss.bitrise.io/t/merge-request-failure-on-git-clone-step-gitlab-private-repo/13198

**Comment by non-binary** [comment]
Hi @raquezha,

Please open a new GitHub ticket on this repo referencing this ticket as it's been a while. Additionally since this is happening with GitLab instead of GitHub.
